### ISSUE TITLE
Flake8 Fails on Amazon LInux 2

### ISSUE THREAD

**Issue by Gamecock** [BrickSchema/Brick#444] opened 2022-10-13 21:04 UTC
Potentially related to the fix for #201 
Also to this issue in flake8: https://github.com/PyCQA/flake8/issues/1701

STeps to reproduce:
checkout out repo, install requirements, install pre-commit
Make minor change to *.py

commit change:

Result:
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

Traceback (most recent call last):
  File "/home/ec2-user/.cache/pre-commit/repox3x2enjw/py_env-python3/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.cache/pre-commit/repox3x2enjw/py_env-python3/lib/python3.7/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/ec2-user/.cache/pre-commit/repox3x2enjw/py_env-python3/lib/python3.7/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/home/ec2-user/.cache/pre-commit/repox3x2enjw/py_env-python3/lib/python3.7/site-packages/flake8/main/application.py", line 350, in _run
    self.initialize(argv)
  File "/home/ec2-user/.cache/pre-commit/repox3x2enjw/py_env-python3/lib/python3.7/site-packages/flake8/main/application.py", line 330, in initialize
    self.find_plugins(config_finder)
  File "/home/ec2-user/.cache/pre-commit/repox3x2enjw/py_env-python3/lib/python3.7/site-packages/flake8/main/application.py", line 153, in find_plugins
    self.check_plugins = plugin_manager.Checkers(local_plugins.extension)
  File "/home/ec2-user/.cache/pre-commit/repox3x2enjw/py_env-python3/lib/python3.7/site-packages/flake8/plugins/manager.py", line 357, in __init__
    self.namespace, local_plugins=local_plugins
  File "/home/ec2-user/.cache/pre-commit/repox3x2enjw/py_env-python3/lib/python3.7/site-packages/flake8/plugins/manager.py", line 238, in __init__
    self._load_entrypoint_plugins()
  File "/home/ec2-user/.cache/pre-commit/repox3x2enjw/py_env-python3/lib/python3.7/site-packages/flake8/plugins/manager.py", line 254, in _load_entrypoint_plugins
    eps = importlib_metadata.entry_points().get(self.namespace, ())
AttributeError: 'EntryPoints' object has no attribute 'get'

Expected:
Passed or linting error.

OS:
cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

Python:
python --version
Python 3.7.10

**Comment by gtfierro** [comment] 2023-02-13 18:55
Closing for now as I can't reproduce, but let me know if there's still an issue!

**Closed by gtfierro** 2023-02-13 18:55 UTC
